familywebsite/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('home.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('logout/', views.logout_view, name='logout'),
]

users/urls.py
from django.urls import path

from users.views import index
from users.views import video
from users.views import document
from users.views import photo

app_name = 'users'
urlpatterns = [
    path('videos/', video.videos, name='videos'),
    path('photos/', photo.photos, name='photos'),
    path('documents/', document.documents, name='documents'),

    path('video/form/<int:key>/', video.VideoForm.as_view(), name='video_form'),
    path('photo/form/<int:key>/', photo.PhotoForm.as_view(), name='photo_form'),
    path('document/form/<int:key>/', document.DocumentForm.as_view(), name='document_form'),

    path('video/<int:key>/', video.watch, name='watch'),
    # path('document/<int:key>/', document.show_document, name='show_document'),

    path('video/delete/<int:key>/', video.delete_video, name='delete_video'),
    path('photo/delete/<int:key>/', photo.delete_photo, name='delete_photo'),
    path('document/delete/<int:key>/', document.delete_document, name='delete_document'),

    path('', index.index, name='index'),
]

users/models.py
from django.contrib.auth.models import User
from django.db import models


PHOTO_EXTENSIONS = [
    'jpeg', 'jpg', 'gif', 'png', 'svg'
]

VIDEO_EXTENSIONS = [
    'avi', 'mp4', 'mov', 'm4v', 'mkv', 'flv', 'wmv', 'mpg', 'mpeg'
]


def get_file_path(instance, filename):
    return 'user_{0}/{1}/{2}'.format(instance.owner.id, get_file_type(filename), filename)


def get_file_type(name):
    arr = name.split('.')
    ext = arr[len(arr)-1].lower()
    if ext in PHOTO_EXTENSIONS:
        return 'images'
    elif ext in VIDEO_EXTENSIONS:
        return 'videos'
    else:
        return 'documents'


class Photo(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    date_uploaded = models.DateTimeField(auto_now_add=True)
    photo = models.FileField(upload_to=get_file_path)
    occasion = models.CharField(max_length=100)
    private = models.BooleanField(default=False)


class Video(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    date_uploaded = models.DateTimeField(auto_now_add=True)
    video = models.FileField(upload_to=get_file_path)
    type = models.CharField(max_length=20)
    extension = models.CharField(max_length=10)
    private = models.BooleanField(default=False)


class Document(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    date_uploaded = models.DateTimeField(auto_now_add=True)
    document = models.FileField(upload_to=get_file_path)
    group = models.CharField(max_length=100)
    private = models.BooleanField(default=False)


class FileShare(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    file_id = models.CharField(max_length=100)
    file_type = models.CharField(max_length=15)











users/forms/document.py
from django.forms import ModelForm

from users.models import Document


class DocumentForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(DocumentForm, self).__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Document
        exclude = ('date_uploaded', 'private')


class EditDocumentForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(EditDocumentForm, self).__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Document
        exclude = ('date_uploaded', 'owner', 'private', 'document')

users/forms/photo.py
from django.forms import ModelForm

from users.models import Photo


class PhotoForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(PhotoForm, self).__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Photo
        exclude = ('date_uploaded', 'private')


class EditPhotoForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(EditPhotoForm, self).__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Photo
        exclude = ('date_uploaded', 'owner', 'private', 'photo')

users/forms/video.py
from django.forms import ModelForm

from users.models import Video


class VideoForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(VideoForm, self).__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Video
        exclude = ('date_uploaded', 'private')


class EditVideoForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(EditVideoForm, self).__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Video
        exclude = ('date_uploaded', 'owner', 'private', 'video', 'extension')

users/controllers/document.py
from django.core.exceptions import ObjectDoesNotExist

from users.models import Document

from users.forms.document import DocumentForm, EditDocumentForm

from users.display_classes import DisplayDocument


class DocumentController:

    def get_document(self, key):
        try:
            return Document.objects.get(id=key)
        except ObjectDoesNotExist:
            return None

    def get_documents(self):
        return list(map(get_display_document, Document.objects.all().order_by('name')))

    def get_form(self, doc):
        if doc is not None:
            return DocumentForm(instance=doc)
        return DocumentForm()

    def new_document(self, info, files):
        form = DocumentForm(info, files)
        if form.is_valid():
            form.save()
        return form

    def edit_document(self, info, doc):
        form = EditDocumentForm(info, instance=doc)
        if form.is_valid():
            form.save()
        return form


def get_display_document(doc):
    return DisplayDocument(doc)

users/controllers/photo.py
from django.core.exceptions import ObjectDoesNotExist

from users.models import Photo

from users.forms.photo import PhotoForm, EditPhotoForm


class PhotoController:

    def get_photo(self, key):
        try:
            return Photo.objects.get(id=key)
        except ObjectDoesNotExist:
            return None

    def get_photos(self):
        return Photo.objects.all()

    def get_form(self, photo):
        if photo is not None:
            return PhotoForm(instance=photo)
        return PhotoForm()

    def new_photo(self, info, files):
        form = PhotoForm(info, files)
        if form.is_valid():
            form.save()
        return form

    def edit_photo(self, info, photo):
        form = EditPhotoForm(info, instance=photo)
        if form.is_valid():
            form.save()
        return form

users/controllers/video.py
from django.core.exceptions import ObjectDoesNotExist

from users.models import Video

from users.forms.video import VideoForm, EditVideoForm

from users.display_classes import DisplayVideo


class VideoController:

    def get_video(self, key):
        try:
            return Video.objects.get(id=key)
        except ObjectDoesNotExist:
            return None

    def get_videos(self):
        return list(map(get_display_video, Video.objects.all().order_by('name')))

    def get_form(self, video):
        if video is not None:
            return VideoForm(instance=video)
        return VideoForm()

    def new_video(self, info, files):
        form = VideoForm(info, files)
        if form.is_valid():
            form.save()
        return form

    def edit_video(self, info, video):
        form = EditVideoForm(info, instance=video)
        if form.is_valid():
            form.save()
        return form


def get_display_video(video):
    return DisplayVideo(video)

users/views/document.py
from django.shortcuts import render, Http404, redirect
from django.views.generic import View

from users.controllers.document import DocumentController


def documents(request):

    if request.method == 'GET':
        controller = DocumentController()
        context = {
            'documents': controller.get_documents(),
        }
        return render(request, 'users/document/index.html', context)

    raise Http404


class DocumentForm(View):
    template_name = 'users/document/form.html'

    def get(self, request, key):
        controller = DocumentController()
        if key > 0:
            context = {
                'document': controller.get_document(key),
                'form': controller.get_form(controller.get_document(key))
            }
        else:
            context = {
                'document': None,
                'form': controller.get_form(None)
            }

        return render(request, self.template_name, context)

    def post(self, request, key):
        controller = DocumentController()
        if key > 0:
            document = controller.get_document(key)
            form = controller.edit_document(request.POST.copy(), document)
            context = {
                'document': controller.get_document(key) if form.errors else form.instance,
                'form': form,
                'message': None if form.errors else {'message': 'Document updated successfully', 'status': 'success'}
            }
            return render(request, self.template_name, context)
        else:
            info = request.POST.copy()
            info['name'] = info['name'] if info['name'] else request.FILES['document'].name
            info['owner'] = self.request.user.id
            form = controller.new_document(info, request.FILES)
            context = {
                'document': None,
                'form': form,
                'message': None if form.errors else {'message': 'Document added successfully', 'status': 'success'}
            }
            return render(request, self.template_name, context)


def delete_document(request, key):

    if request.method == 'GET':
        controller = DocumentController()
        document = controller.get_document(key)
        if document is not None:
            document.delete()
            return redirect('users:documents')
        else:
            raise Http404

    raise Http404

users/views/index.py
from django.shortcuts import render


def index(request):

    return render(request, 'users/index.html')

users/views/photo.py
from django.shortcuts import render, Http404, redirect
from django.views.generic import View

from users.controllers.photo import PhotoController


def photos(request):

    if request.method == 'GET':
        controller = PhotoController()
        context = {
            'photos': controller.get_photos(),
        }
        return render(request, 'users/photos/index.html', context)

    raise Http404


class PhotoForm(View):
    template_name = 'users/photos/form.html'

    def get(self, request, key):
        controller = PhotoController()
        if key > 0:
            context = {
                'photo': controller.get_photo(key),
                'form': controller.get_form(controller.get_photo(key))
            }
        else:
            context = {
                'photo': None,
                'form': controller.get_form(None)
            }

        return render(request, self.template_name, context)

    def post(self, request, key):
        controller = PhotoController()
        if key > 0:
            photo = controller.get_photo(key)
            form = controller.edit_photo(request.POST.copy(), photo)
            context = {
                'photo': controller.get_photo(key) if form.errors else form.instance,
                'form': form,
                'message': None if form.errors else {'message': 'Photo updated successfully', 'status': 'success'}
            }
            return render(request, self.template_name, context)
        else:
            info = request.POST.copy()
            info['name'] = info['name'] if info['name'] else request.FILES['photo'].name
            info['owner'] = self.request.user.id
            form = controller.new_photo(info, request.FILES)
            context = {
                'photo': None,
                'form': form,
                'message': None if form.errors else {'message': 'Photo added successfully', 'status': 'success'}
            }
            return render(request, self.template_name, context)


def delete_photo(request, key):

    if request.method == 'GET':
        controller = PhotoController()
        photo = controller.get_photo(key)
        if photo is not None:
            photo.delete()
            return redirect('users:photos')
        else:
            raise Http404

    raise Http404

users/views/video.py
from django.shortcuts import render, Http404, redirect
from django.views.generic import View

from users.controllers.video import VideoController


def videos(request):

    if request.method == 'GET':
        controller = VideoController()
        context = {
            'videos': controller.get_videos(),
        }
        return render(request, 'users/video/index.html', context)

    raise Http404


class VideoForm(View):
    template_name = 'users/video/form.html'

    def get(self, request, key):
        controller = VideoController()
        if key > 0:
            context = {
                'video': controller.get_video(key),
                'form': controller.get_form(controller.get_video(key))
            }
        else:
            context = {
                'video': None,
                'form': controller.get_form(None)
            }

        return render(request, self.template_name, context)

    def post(self, request, key):
        controller = VideoController()
        if key > 0:
            video = controller.get_video(key)
            form = controller.edit_video(request.POST.copy(), video)
            context = {
                'video': controller.get_video(key) if form.errors else form.instance,
                'form': form,
                'message': None if form.errors else {'message': 'Video updated successfully', 'status': 'success'}
            }
            return render(request, self.template_name, context)
        else:
            info = request.POST.copy()
            info['name'] = info['name'] if info['name'] else request.FILES['video'].name
            info['owner'] = self.request.user.id
            arr = request.FILES['video'].name.split('.')
            if len(arr) > 1:
                ext = arr[len(arr) - 1]
                info['extension'] = ext
            form = controller.new_video(info, request.FILES)
            context = {
                'video': None,
                'form': form,
                'message': None if form.errors else {'message': 'Video added successfully', 'status': 'success'}
            }
            return render(request, self.template_name, context)


def delete_video(request, key):

    if request.method == 'GET':
        controller = VideoController()
        video = controller.get_video(key)
        if video is not None:
            video.delete()
            return redirect('users:videos')
        else:
            raise Http404

    raise Http404


def watch(request, key):

    if request.method == 'GET':
        controller = VideoController()
        context = {
            'video': controller.get_video(key)
        }
        return render(request, 'users/video/watch.html', context)

    raise Http404

users/templates/users/video/form.html
{% extends 'users/template.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                {% if message %}
                    <div class="alert alert-{{ message.status }}">
                        <button type="button" aria-hidden="true" class="close" data-dismiss="alert">
                            <i class="nc-icon nc-simple-remove"></i>
                        </button>
                        <span>{{ message.message }}</span>
                    </div>
                {% endif %}
                {% if form.errors %}
                    <div class="alert alert-danger">
                        <button type="button" aria-hidden="true" class="close" data-dismiss="alert">
                            <i class="nc-icon nc-simple-remove"></i>
                        </button>
                        <span>{{ form.errors }}</span>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <div class="card stacked-form">
                    <div class="card-header ">
                        <h4 class="card-title">
                            {% if video %}
                                Modifier {{ video.name }}
                            {% else %}
                                Nouvelle video
                            {% endif %}
                        </h4>
                    </div>
                    <div class="card-body ">
                        {% if video %}
                            <form method="post" action="{% url 'users:video_form' key=video.id %}">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label>Name</label>
                                    {{ form.name }}
                                </div>
                                <div class="form-group">
                                    <label>Type</label>
                                    <select name="type" class="selectpicker" data-title="Video type"
                                            data-style="btn-default btn-outline" data-menu-style="dropdown-blue">
                                        <option value="movie">Movie</option>
                                        <option value="series">Series</option>
                                        <option value="other">Other</option>
                                    </select>
                                </div>
                                <button class="btn btn-success" type="submit">Sauvegarder</button>
                            </form>
                        {% else %}
                            <form method="post" action="{% url 'users:video_form' key=0 %}"
                                  enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label>Name</label>
                                    <input type="text" name="name" class="form-control"/>
                                    <small class="form-text text-muted">* Leave name blank to use file name.</small>
                                </div>
                                <div class="form-group">
                                    <label>Type</label>
                                    <select name="type" class="selectpicker" data-title="Video type"
                                            data-style="btn-default btn-outline" data-menu-style="dropdown-blue">
                                        <option value="movie">Movie</option>
                                        <option value="series">Series</option>
                                        <option value="other">Other</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Video</label>
                                    {{ form.video }}
                                </div>
                                <button class="btn btn-success" type="submit">Enregistrer</button>
                            </form>
                        {% endif %}
                    </div>
                </div>

            </div>
        </div>
        <a href="{% url 'users:videos' %}" class="btn btn-lg btn-default">Return to video list</a>
    </div>
{% endblock %}

users/templates/users/video/index.html
{% extends 'users/template.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <a href="{% url 'users:video_form' key=0 %}" class="btn btn-primary btn-lg p-4">
                    Nouvelle video
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card bootstrap-table">
                    <div class="card-body table-full-width">
                        <div class="toolbar">
                            <!--        Here you can write extra buttons/actions for the toolbar              -->
                        </div>
                        <table id="bootstrap-table" class="table">
                            <thead>
                            <tr>
                                <th data-field="name" data-sortable="true">Name</th>
                                <th data-field="type" data-sortable="true">Type</th>
                                <th data-field="date" data-sortable="true">Date</th>
                                <th data-field="size" data-sortable="true">Size</th>
                                <th data-field="actions" class="td-actions text-right">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for x in videos %}
                                <tr>
                                    <td><a class="text-dark" href="{% url 'users:watch' key=x.id %}" target="_blank"><strong>{{ x.name }}</strong></a></td>
                                    <td>{{ x.type }}</td>
                                    <td>{{ x.date_uploaded }}</td>
                                    <td>{{ x.size }}MB</td>
                                    <td>
                                        <a rel="tooltip" title="Edit" class="btn btn-link btn-warning table-action"
                                           href="{% url 'users:video_form' key=x.id %}">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <a rel="tooltip" title="Remove" class="btn btn-link btn-danger table-action"
                                           href="{% url 'users:delete_video' key=x.id %}">
                                            <i class="fa fa-remove"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        let $table = $('#bootstrap-table');

        $().ready(function () {

            $table.bootstrapTable({
                toolbar: ".toolbar",
                clickToSelect: true,
                search: true,
                pagination: true,
                searchAlign: 'left',
                pageSize: 8,
                pageList: [8, 10, 25, 50],

                formatShowingRows: function (pageFrom, pageTo, totalRows) {
                    //do nothing here, we don't want to show the text "showing x of y from..."
                },
                formatRecordsPerPage: function (pageNumber) {
                    return pageNumber + " rows visible";
                },
                icons: {
                    detailOpen: 'fa fa-plus-circle',
                    detailClose: 'fa fa-minus-circle'
                }
            });

            //activate the tooltips after the data table is initialized
            $('[rel="tooltip"]').tooltip();

            $(window).resize(function () {
                $table.bootstrapTable('resetView');
            });


        });
    </script>
{% endblock %}

users/templates/users/video/watch.html
{% extends 'users/template.html' %}

{% block content %}
    <div class="container">
        <h2>{{ video.name }}</h2>
        {% if video.extension == 'mp4' %}
            <video width="640" height="480" controls>
                <source src="{{ video.video.url }}" type="video/mp4">
                Video cannot be viewed.
            </video>
        {% else %}
            <object data="{{ video.video.url }}" width="360" height="250">
                <param name="src" value="{{ video.video.url }}" />
            </object>
        {% endif %}
    </div>
{% endblock %}